name: Publish to NPM

on:
  release:
    types: [created]
  # push:
  #   branches:
  #     - 'main'

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - uses: pnpm/action-setup@v2.2.2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: latest
  #         cache: pnpm

  #     - run: pnpm install --frozen-lockfile

  #     - name: Run Linting
  #       run: pnpm lint

  #     # - name: Run Tests
  #     #   run: pnpm test

  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - uses: pnpm/action-setup@v2.2.2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: latest
  #         cache: pnpm
  #         registry-url: https://registry.npmjs.org/

  #     - run: pnpm install --frozen-lockfile

  #     - run: pnpm build

  #     - run: pnpm publish package/ --no-git-checks
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm lint

      # - name: Run Test
      #   run: pnpm test

      - name: Run Build
        run: pnpm build

      - run: pnpm publish package/ --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
